/**
 * this file contains function definitions needed
 * by the timer thread.
 * The timer thread is responsible for determining
 * when the user has stopped playing and so an output
 * must be generated by the Echo State Network
 * Author: Charlie Street
 */

#ifndef FYP_TIMERTHREAD_H
#define FYP_TIMERTHREAD_H

#include "globalState.h"

/**
 * the function to be run within the thread
 * for the timing functionality of the system
 * @param state the global state of the system
 */
void timerWorker(const shared_ptr<globalState> &state);

#endif //FYP_TIMERTHREAD_H
